spring:
  application:
    name: authorization-server

  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
  datasource:
    url: jdbc:mysql://mysql-server:3307/coin-exchange?useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wangzheng
#  redis:
#    host: redis-server
#    port: 6380
server:
  port: 9999